### PR TITLE
Fix RTD builds of UG and DG (closes #1127)

### LINKED ISSUE #1127: RTD builds failing for user and dev guides
After updating to the latest Sphinx (3.5.0) the documentation fails to build with:

    AttributeError: 'str' object has no attribute 'priority'

this is discussed here: https://github.com/sphinx-doc/sphinx/issues/8885

It seems we just need to update `html_context` in `conf.py` to use `html_css_files` instead.

### PR DESCRIPTION
**Pull request by arporter**
According to https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files, `html_css_files` has been supported since version 1.8 of Sphinx so this change should be fine with older versions too.

### CODE REVIEW

**Comment by arporter** [comment]
A tiny PR that just fixes the `conf.py` files of the User and Dev guides so that RTD works (because it's recent upgrade to 3.5.0 of Sphinx causes build failures).

**Review by TeranIvy — CHANGES_REQUESTED** [review]
I reproduced the error
```
    ctx['css_files'].sort(key=lambda js: js.priority)
AttributeError: 'str' object has no attribute 'priority'
```
when trying to build documentation on master with Sphinx 3.5.0. Interestingly enough, it doesn't happen with Sphinx 3.5.1. The changes in configuration file on the branch remove the error.
I can also confirm that the error is not present in (quite old) Sphinx 2.2.0 that we have in the LFRic Python.

There are two `pylint` errors about the constant name "needs_sphinx" not being upper case (see inline).

Tests run with compilation and examples run. Documentation builds on the branch with Sphinx 3.5.0, 3.5.1 and 2.2.0.

I get a warning with the developer guide, though:
```
checking consistency... $PSYCLONE_DIR/PSyclone/doc/developer_guide/developers_gocean1p0_stencils.rst: WARNING: document isn't included in any toctree
```
I am aware this warning is not related to this PR. Is there an issue for it that can be referenced in the developer guide?

File: doc/developer_guide/conf.py [hunk 1]
```diff
@@ -23,8 +23,8 @@
 # -- General configuration ----------------------------------------------------
 
 # If your documentation needs a minimal Sphinx version, state it here.
-# We need version >= 1.3 for the "numref" feature.
-needs_sphinx = '1.3'
+# We need version >= 1.8 for the html_css_files feature.
+needs_sphinx = '1.8'
```
[the remark this answers is not in the document]
Comment (arporter) [reply doc/developer_guide/conf.py:27]: Since these are Sphinx keywords, I don't think I can do anything about this warning and obviously the same goes for `user_guide/conf.py`.

[the remark this answers is not in the document]
Comment (arporter) [reply doc/developer_guide/conf.py:33]: Actually, that being so, I've just disabled the 'invalid-name' pylint warnings in the two files.

[the remark this answers is not in the document]
Comment (TeranIvy) [reply doc/developer_guide/conf.py:33]: Good idea, as there are other lower-case Sphinx keywords.

**Review by TeranIvy — APPROVED** [review]
All well now. Proceeding to merge.
