### PR TITLE
ASCII extraction

### PR DESCRIPTION
**Pull request by hiker**
This adds an ASCII extraction library. I have also added an example for extraction of generic kernels (though atm we can't create drivers for it. I know I had nemo extraction+driver hacked in the past to work (hence this example that I never committed). With the work on moving to PSyIR (#1010) and refactoring kernel extraction into a common base class, we should be very close to also allow driver creation here.

### CODE REVIEW

**Comment by hiker** [comment]
Hmm - the nvfortran compilation of the new nemo.eg7 example failed:
```
make -C eg7 compile
make[2]: Entering directory '/home/gh_runner/actions-runner/_work/PSyclone-mirror/PSyclone-mirror/examples/nemo/eg7'
psyclone -l output --config /home/gh_runner/actions-runner/_work/PSyclone-mirror/PSyclone-mirror/config/psyclone.cfg -l all -s ./extract_kernels.py -o psy.f90 \
   ../code/tra_adv.F90
Ignoring error 'Transformation Error: Nodes of type 'CodeBlock' cannot be enclosed by a ExtractTrans transformation but found:
! PSyclone CodeBlock (unsupported code) reason:
!  - Unsupported statement: Write_Stmt
WRITE(4, *) mydomain(ji, jj, jk)
'.
nvfortran -acc -Minfo=all -I../../../lib/extract/standalone/generic -I../../../lib/extract/standalone -c psy.f90
tra_adv:
    287, Recognized memory zero idiom
    288, Recognized memory zero idiom
    334, Recognized memory zero idiom
    335, Recognized memory zero idiom
    490, FMA (fused multiply-add) instruction(s) generated
    491, FMA (fused multiply-add) instruction(s) generated
    492, FMA (fused multiply-add) instruction(s) generated
    493, FMA (fused multiply-add) instruction(s) generated
    496, FMA (fused multiply-add) instruction(s) generated
    497, FMA (fused multiply-add) instruction(s) generated
    498, FMA (fused multiply-add) instruction(s) generated
    499, FMA (fused multiply-add) instruction(s) generated
    566, Recognized memory zero idiom
    567, Recognized memory zero idiom
    590, Recognized memory zero idiom
    720, FMA (fused multiply-add) instruction(s) generated
    721, FMA (fused multiply-add) instruction(s) generated
    722, FMA (fused multiply-add) instruction(s) generated
    723, FMA (fused multiply-add) instruction(s) generated
nvfortran psy.o -o traadv-standalone.exe ../../../lib/extract/standalone/generic/lib_extract.a 
/usr/bin/ld: psy.o:(.init_array+0x10): undefined reference to `__acc_compiled'
make[2]: *** [Makefile:96: traadv-standalone.exe] Error 2
make[2]: Leaving directory '/home/gh_runner/actions-runner/_work/PSyclone-mirror/PSyclone-mirror/examples/nemo/eg7'
```
But it works fine with my nvfortran 23.5-0:
```
F90FLAGS="-acc -Minfo=all" F90=nvfortran make compile
psyclone -l output --config /home/joerg/work/psyclone/config/psyclone.cfg -l all -s ./extract_kernels.py -o psy.f90 \
   ../code/tra_adv.F90
/home/joerg/.local/bin/psyclone:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('PSyclone==3.1.1.dev0')
Ignoring error 'Transformation Error: Nodes of type 'CodeBlock' cannot be enclosed by a ExtractTrans transformation but found:
! PSyclone CodeBlock (unsupported code) reason:
!  - Unsupported statement: Write_Stmt
WRITE(4, *) mydomain(ji, jj, jk)
'.
nvfortran -acc -Minfo=all -I../../../lib/extract/standalone/generic -I../../../lib/extract/standalone -c psy.f90
tra_adv:
    287, Memory zero idiom, loop replaced by call to __c_mzero8
    288, Memory zero idiom, loop replaced by call to __c_mzero8
    334, Memory zero idiom, loop replaced by call to __c_mzero8
    335, Memory zero idiom, loop replaced by call to __c_mzero8
    490, FMA (fused multiply-add) instruction(s) generated
    491, FMA (fused multiply-add) instruction(s) generated
    492, FMA (fused multiply-add) instruction(s) generated
    493, FMA (fused multiply-add) instruction(s) generated
    496, FMA (fused multiply-add) instruction(s) generated
    497, FMA (fused multiply-add) instruction(s) generated
    498, FMA (fused multiply-add) instruction(s) generated
    499, FMA (fused multiply-add) instruction(s) generated
    566, Memory zero idiom, loop replaced by call to __c_mzero8
    567, Memory zero idiom, loop replaced by call to __c_mzero8
    590, Memory zero idiom, loop replaced by call to __c_mzero8
    720, FMA (fused multiply-add) instruction(s) generated
    721, FMA (fused multiply-add) instruction(s) generated
    722, FMA (fused multiply-add) instruction(s) generated
    723, FMA (fused multiply-add) instruction(s) generated
nvfortran psy.o -o traadv-standalone.exe ../../../lib/extract/standalone/generic/lib_extract.a 

```
I might need some help here, so declaring this ready for a review and help :)

Oh, nemo5 is also failing, but that appears to be failing regularly? Doesn't appear to be related to anything I am doing here(?)

File: doc/user_guide/psyke.rst [hunk 1]
```diff
@@ -374,16 +374,27 @@ run, and it will create two kernel data files.
...
+  same binary representation. This can show up as small errors reported
+  when running the drivers, even for trivial operations like `x-y`.
+
+The best option for portability across different compilers and different
+hardware is the NetCDF extraction library.
+
+The three extraction :ref:`libraries <libraries>` are in
 `lib/extract/standalone
-<https://github.com/stfc/PSyclone/tree/master/lib/extract/standalone>`_.
+<https://github.com/stfc/PSyclone/tree/master/lib/extract/standalone>`_,
```
Comment (sergisiso) [inline doc/user_guide/psyke.rst]: It may be a pain to do it everywhere, but I think it would be clearer if now we rename this one as "standalone_binary" also in the docs/tutorials/gitingores that reference it..

File: doc/user_guide/psyke.rst [hunk 2]
```diff
@@ -374,16 +374,27 @@ run, and it will create two kernel data files.
...
 --------------------
-PSyclone comes with two extraction libraries: one is based on NetCDF
-and will create NetCDF files to contain all input- and output-parameters.
-The second one is a stand-alone library which uses only standard Fortran
-IO to write and read kernel data. The binary files produced using this
-library may not be portable between machines and compilers. If you
-require such portability then please use the NetCDF extraction library.
-
-The two extraction :ref:`libraries <libraries>` are in
+PSyclone comes with three extraction libraries:
```
Comment (sergisiso) [inline doc/user_guide/psyke.rst:377]: Looking at this file more generally I think we can do some improvements:

- Essentially, I think the "Mechanism" section is duplicated, the restrictions are better explained in the "Restrictions" sections and the part below in the "use" section. The only part I would keep is the last paragraph that I would put in the introduction paragraph as: "PSyKE uses the [PSyData API] which relies on generic Fortran interfaces to provide multiple implementations (extraction libraries) that can be chosen at link-time."
- Then I would move the "Restrictions" inside the "Use" (use "Usage") section. And the "Extraction for generic Fortran" as the first category in "Extraction libraries" e.g;
```
- Introduction
- Usage
   - Restrictions
- Extraction libraries
   - Extraction for generic Fortran
   ...
```

File: doc/user_guide/psyke.rst [hunk 3]
```diff
@@ -408,14 +419,16 @@ Extraction for GOcean
...
+<https://github.com/stfc/PSyclone/tree/master/lib/extract/standalone_ascii/dl_esm_inf>`_
 and 
 `lib/extract/netcdf/dl_esm_inf
 <https://github.com/stfc/PSyclone/tree/master/lib/extract/netcdf/dl_esm_inf>`_
 implement the full PSyData API for use with the
 :ref:`GOcean <gocean-api>` dl_esm_inf infrastructure library.
-When running the instrumented executable, it will create either a binary or
-a NetCDF file for each instrumented
+When running the instrumented executable, it will create a corresponding
+kernel data file for each instrumented
```
Comment (sergisiso) [inline doc/user_guide/psyke.rst]: Remove "kernel"

File: doc/user_guide/psyke.rst [hunk 4]
```diff
@@ -427,9 +440,9 @@ variable ``xyz`` will have its
 sizes stored as ``xyzdim1``, ``xyzdim2`` for the input values,
 and output arrays use the name ``xyz_postdim1``, ``xyz_postdim2``.
 
-.. note:: The stand-alone library does not store the names of the
-    variables in the output file, but these names will be used
-    as variable names in the created driver.
+.. note:: The stand-alone libraries do not store the names of the
+    variables in the output file, but these are the variable names
```
Comment (sergisiso) [inline doc/user_guide/psyke.rst]: s/are/will match/ ?

File: examples/nemo/README.md [hunk 5]
```diff
@@ -146,3 +146,11 @@ shows the extraction of kernel input- and output-data.
...
 is not modified, e.g. by out-of-bounds accesses to other variables.
 This uses the PSyData interface to instrument generic Fortran code.
+
+## Example 7
+
+A simple stand-alone example that shows how data can be extracted for
+each loop nest using PSyclone's kernel extraction feature PSyKE. Note
+that creation of a driver program (which reads the data files,
+execute the original loop and then compares the results) is not yet
+support for generic transformations.
```
Comment (sergisiso) [inline examples/nemo/README.md]: supported

File: lib/extract/standalone_ascii/lfric/.gitignore [hunk 6]
```diff
@@ -0,0 +1,3 @@
+kernel_data_standalone_ascii.f90
+compare_variables_mod.F90
+extract_standalone_base.F90
```
Comment (sergisiso) [inline lib/extract/standalone_ascii/lfric/.gitignore]: linebreak missing

File: lib/extract/standalone_ascii/dl_esm_inf/kernel_data_standalone_ascii.f90 [hunk 7]
```diff
@@ -0,0 +1,131 @@
...
+    ! -------------------------------------------------------------------------
+    !> This subroutine declares a double precision field as defined in
+    !! dl_esm_info (r2d_field). A corresponding variable definition is added
+    !! to the ASCII file.
+    !! @param[in,out] this The instance of the extract_PsyDataType.
+    !! @param[in] name The name of the variable (string).
+    !! @param[in] value The value of the variable.
+    subroutine DeclareFieldDouble(this, name, value)
+
+        use field_mod, only : r2d_field
```
Comment (sergisiso) [inline lib/extract/standalone_ascii/dl_esm_inf/kernel_data_standalone_ascii.f90]: Just double checking, is this type the only reason we need the "dl_esm_inf" library extraction specialisation? What changes would we need in the gocean driver creation to be able to drop this specialisation/folder?

File: lib/extract/standalone_ascii/lfric/kernel_data_standalone_ascii.jinja [hunk 8]
```diff
@@ -0,0 +1,347 @@
...
+        implicit none
+
+        class(extract_PSyDataType), intent(inout), target :: this
+        character(*), intent(in)                          :: name
+        type(field_r{{prec}}_type), intent(in)                  :: value
+
+        type(field_r{{prec}}_proxy_type) :: value_proxy
+
+        value_proxy = value%get_proxy()
+        call this%PreDeclareVariable(name, value_proxy%data)
```
Comment (sergisiso) [inline lib/extract/standalone_ascii/lfric/kernel_data_standalone_ascii.jinja]: Same here, not for this PR but I need to understand what we are missing to drop this specialisations. Are we still providing the field_types and need the get_proxy(), didn't the lowering meant that we already get the "%data"/"_data" fields?

File: doc/user_guide/psyke.rst (hunk 1 above)
Comment (hiker) [reply doc/user_guide/psyke.rst]: Very good point - but what about we rename them both: `binary` and `ascii` ? This way the three library names are quite symmetrical, just specifying the output format.

Comment (sergisiso) [reply doc/user_guide/psyke.rst]: Sounds good

Comment (hiker) [reply doc/user_guide/psyke.rst]: All done. It was a total pain, but totally worth it- everything sounds so much better now, is consistent, and the names are shorter :)

File: doc/user_guide/psyke.rst (hunk 2 above)
Comment (hiker) [reply doc/user_guide/psyke.rst:377]: I agree with the restructuring, but not that mechanism is duplicated :) That section explains the API-specific transformations, and is actually the first to show the created Fortran code (which is in the usage as well, but without any explanation). So, I have restructured the doc as you suggested, and have moved some sections from the previous ``Mechanism`` section into various places in usage. I also moved the LFRic restrictions section into the general restricted section.

I did not modify the extraction library section, mainly because I agree with you that all the domain-specific libraries can likely go, so I didn't want to waste additional time on that (and do this as part of #3044).

File: doc/user_guide/psyke.rst (hunk 3 above)
Comment (hiker) [reply doc/user_guide/psyke.rst]: Done

File: doc/user_guide/psyke.rst (hunk 4 above)
Comment (hiker) [reply doc/user_guide/psyke.rst]: Done

File: examples/nemo/README.md (hunk 5 above)
Comment (hiker) [reply examples/nemo/README.md]: Done.

File: lib/extract/standalone_ascii/lfric/.gitignore (hunk 6 above)
Comment (hiker) [reply lib/extract/standalone_ascii/lfric/.gitignore]: Done.

File: lib/extract/standalone_ascii/dl_esm_inf/kernel_data_standalone_ascii.f90 (hunk 7 above)
Comment (hiker) [reply lib/extract/standalone_ascii/dl_esm_inf/kernel_data_standalone_ascii.f90]: I agree, see #3044.

File: lib/extract/standalone_ascii/lfric/kernel_data_standalone_ascii.jinja (hunk 8 above)
Comment (hiker) [reply lib/extract/standalone_ascii/lfric/kernel_data_standalone_ascii.jinja]: Same :)
